### PR TITLE
added support for docker image creation

### PR DESCRIPTION
**Pull request by tunix**

### CODE REVIEW

**Comment by tunix** [comment]
👍

**Comment by tunix** [comment]
👍

**Comment by mustafaersahin** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/monitise-mea/gerrit-dashboard-server/pull-request/13/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=monitise-mea/gerrit-dashboard-server)

**Comment by tunix** [comment]
👍

**Comment by tunix** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/monitise-mea/gerrit-dashboard-server/pull-request/13/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=monitise-mea/gerrit-dashboard-server)

**Comment by tunix** [comment]
👍

**Comment by tunix** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/monitise-mea/gerrit-dashboard-server/pull-request/13/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=monitise-mea/gerrit-dashboard-server)

**Pull request merged**
