### PR TITLE
standart filter mechanism applied to following stats.

### PR DESCRIPTION
**Pull request by mustafaersahin**
-AverageMergeDuration
-AverageFirstReviewDuration

### CODE REVIEW

**Comment by mustafaersahin** [comment]
Approved

**Comment by tunix** [comment]
Approved

**Comment by tunix** [comment]
👍

**Comment by tunix** [comment]
Approved

**Comment by tunix** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/monitise-mea/gerrit-dashboard-server/pull-request/19/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=monitise-mea/gerrit-dashboard-server)

**Comment by tunix** [comment]
@mustafaersahin - can you please update your PR for latest changes in master?

**Comment by tunix** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/monitise-mea/gerrit-dashboard-server/pull-request/19/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=monitise-mea/gerrit-dashboard-server)

**Comment by mustafaersahin** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/monitise-mea/gerrit-dashboard-server/pull-request/19/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=monitise-mea/gerrit-dashboard-server)

**Comment by tunix** [comment]
thanks!

**Pull request merged**
